stages:
  - test

pytest:
  stage: test
  image:
    name: python:3.10
  before_script:
    - 'echo $PATH'
    - 'pip install -U pip'
    - 'pip install -r requirements.txt'
    - 'python3 setup.py install'
  script:
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
