version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_install:
      - pip install -r requirements.txt
      - python3 setup.py install
# More at https://docs.readthedocs.io/en/stable/build-customization.html
