version: 2
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
  jobs:
    pre_install:
      - pip install -r requirements.txt
      - python3 setup.py install
# More at https://docs.readthedocs.io/en/stable/build-customization.html
# Warning: readthedocs still uses sphinx 1.8.6 as of Nov2022
